#!/bin/bash

# Date format, for use as the prompt.
date=$(date +"%a %d. %b %R")

# gruvbox Colorscheme
foreground="#ebdbb2"
background="#303030"
selected="#fe8019"

fontname="Mononoki Nerd Font:size=10"

# dmenu cannot display more than 30 lines, to avoid screen clutter. Only relevant if you have more than 30 windows open.
height=$(wmctrl -l | wc -l)
if [[ $height -gt 30 ]]
	then heightfit=30
	else heightfit=$height
fi

num=$(wmctrl -l | sed 's/  / /' | cut -d " " -f 4- | nl -w 3 -n rn | sed -r 's/^([ 0-9]+)[ \t]*(.*)$/\1 - \2/' | dmenu -i -p "$date" -l $heightfit -fn "$fontname" -nb $background -nf $foreground -sb $selected -sf $background | cut -d '-' -f -1)

[[ -z "$num" ]] && exit

## Switch to the desktop containing the window <WIN>, raise the window, and give it focus
#wmctrl -l | sed -n "$num p" | cut -c -10 | xargs wmctrl -i -a

# Move the window <WIN> to the current desktop, raise the window, and  give  it focus.
wmctrl -l | sed -n "$num p" | cut -c -10 | xargs wmctrl -i -R
